### ISSUE TITLE
update shinyproxy

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/shinyproxy#3]
The new version contains a patch related to SAML errors.

1) update `jar` file to the latest shinyproxy version
2) update dockerfile to use the new jar file

https://www.shinyproxy.io/downloads/#302

**Comment by DanWismer** [comment]
@jeffreyhanson I can't seem to push my updates becuase the .jar file is over 100 MB limit:

![image](https://github.com/NCC-CNC/shinyproxy/assets/29556279/5867dac7-6ba7-4845-8e70-ea8baefc2070)

**Comment by DanWismer** [comment]
... I initialized LFS for *.jar files. I was able to push after that!

**Comment by DanWismer** [comment]
this is the new JS error: `Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR`

**Comment by jeffreyhanson** [comment]
Thanks for looking into this! Yeah, Git LFS is one way to achieve this. However, AFAIK using Git LFS with GitHub can be pretty costly, so I would recommend avoiding this. This is because GitHub has a relatively small free tier for Git LFS which corresponds to (i) total LFS file size on GitHub and (ii) downloading/cloning LFS files. Once exceeded, GitHub will start charging according to the total file size on GitHub and how often the files are downloaded/cloned. To avoid this, I'd suggest updating the Dockerfile to download the jar file during the build? E.g, similar to the process for setting up Gurobi in the other docker image. How does that sound?

**Comment by DanWismer** [comment]
@jeffreyhanson, 

I mounted the .jar file as a volume: https://github.com/NCC-CNC/shinyproxy/commit/ab8d8fce659af1e20b579bf52a3307454560d28e

Was this what you were thinking? Also how do I test this?

**Comment by DanWismer** [comment]
I tried `docker-compose up -d` and the image built. However I can't view it on http://localhost:3838/

I checked the logs and I don't see anything that jumps out:

![image](https://github.com/NCC-CNC/shinyproxy/assets/29556279/7c25e00a-5865-4415-ae28-5f618af9e00d)

**Comment by DanWismer** [comment]
ah the url I need to view it on is http://localhost:8080/ 

However I am getting an error now 
![image](https://github.com/NCC-CNC/shinyproxy/assets/29556279/a719d2cb-1bef-4726-9de1-5fcea2c4e7ac)


What I am reading is that it may have to do with the template html files. I think I need to edit some template stuff: 

https://support.openanalytics.eu/t/shinyproxy-3-0-0-update-template/2488

**Comment by DanWismer** [comment]
I have it working now! 

What I did was download the updated templates. I then copied those into the docker container, as well as edited the application.yml template-path: config to point to  `/opt/shinyproxy/templates/modified_navbar`

I now need to test this somehow locally to make sure this didn't break anything when using custom templates within the web-apps repo.
